import turtle as trtl

trtl.speed(100)
trtl.goto(0, -10)
trtl.color("black")
trtl.fillcolor("brown")
trtl.begin_fill()
trtl.right(10)
trtl.fd(40)
trtl.circle(12, 200)
trtl.goto(0, -10)
trtl.penup()
trtl.left(194)
trtl.fd(40)
trtl.pendown()
trtl.circle(12, 200)
trtl.goto(0, -10)
trtl.penup()
trtl.left(193)
trtl.fd(40)
trtl.pendown()
trtl.circle(12, 200)
trtl.goto(0, -10)
trtl.penup()
trtl.left(193.5)
trtl.fd(40)
trtl.pendown()
trtl.circle(12, 200)
trtl.goto(0, -10)
trtl.penup()
trtl.left(193)
trtl.fd(40)
trtl.pendown()
trtl.circle(12, 200)
trtl.goto(0, -10)
trtl.penup()
trtl.left(193.5)
trtl.fd(40)
trtl.pendown()
trtl.circle(12, 200)
trtl.goto(0, -10)
trtl.end_fill()

trtl.penup()
trtl.goto(0, -30)
trtl.fillcolor(("#fdaa48"))
trtl.pendown()
trtl.begin_fill()
trtl.circle(20)
trtl.end_fill()

trtl.penup()
trtl.goto(0, 5)
trtl.fillcolor(("#f8481c"))
trtl.pendown()
trtl.begin_fill()
trtl.circle(12)
trtl.end_fill()

trtl.penup()
trtl.goto(-5, -50)
trtl.fillcolor(("yellow"))
trtl.pencolor("black")
trtl.pendown()
trtl.begin_fill()
trtl.left(90)
trtl.fd(20)
trtl.right(90)
trtl.fd(4)
trtl.right(90)
trtl.fd(20)
trtl.right(90)
trtl.fd(4)
trtl.end_fill()

trtl.penup()
trtl.goto(0, 5)
trtl.goto(5, -50)
trtl.left(185)
trtl.fillcolor(("yellow"))
trtl.pencolor("black")
trtl.pendown()
trtl.begin_fill()
trtl.left(90)
trtl.fd(20)
trtl.right(90)
trtl.fd(4)
trtl.right(90)
trtl.fd(20)
trtl.right(90)
trtl.fd(4)
trtl.end_fill()


#trtl.circle(12, 200)
#trtl.goto(0, 0)


wn = trtl.Screen()
wn.mainloop()